fix: add `pyvirtualdisplay` module on test requirements.
What
====

Insert `pyvirtualdisplay` module on manga-py's requirements.

Why
===

- Run project tests, then get a error because `pyvirtualdisplay` module will not be found.
- Resolve that using pip feature called [recursive requirements](https://pip.pypa.io/en/stable/reference/pip_install/#example-requirements-file).
    - Recursive requirements refers (reuse) one requirements-file onto another requirements-file.
    - Explanations:
        - https://pip.pypa.io/en/stable/reference/pip_install/#example-requirements-file
        - https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format
        - https://stackoverflow.com/questions/11704287/split-requirements-files-in-pip
    - Refer from `./requirements_dev.txt` to: 1) `./requirements.txt` + `pyvirtualdisplay`;

Where
=====

On `./requirements_dev.txt` file.

How
===

Steps to reproduce the error and to resolve it:

1. create a **clean (new)** virtual-env;
    ```
    $ python3 -m venv my_env
    $ ls
    my_env
    ```
2. clone manga-py repo;
    ```
    $ git clone https://github.com/paulolimac/manga-py.git
    Cloning into 'manga-py'...
    remote: Enumerating objects: 60, done.
    remote: Counting objects: 100% (60/60), done.
    remote: Compressing objects: 100% (45/45), done.
    remote: Total 10917 (delta 21), reused 34 (delta 14), pack-reused 10857
    Receiving objects: 100% (10917/10917), 23.82 MiB | 576.00 KiB/s, done.
    Resolving deltas: 100% (8487/8487), done.
    ```
3. activate virtual-env;
    ```
    $ source my_env/bin/activate
    (my_env) $
    ```
4. see manga-py `./requirements`, under a virtual-env;
    ```
    (my_env) $ cat ./requirements.txt
    lxml
    cssselect
    Pillow
    requests
    pycryptodome
    cloudscraper
    progressbar2
    urllib3
    packaging
    html-purifier
    selenium
    pyexecjs
    numpy
    loguru
    ```
5. see installed modules, under a virtual-env;
    ```
    (my_env) $ pip freeze
    pkg-resources==0.0.0
    ```
6. install manga-py `./requirements`, under a virtual-env;
    ```
    (my_env) $ pip install -r ./requirements.txt
    Collecting lxml (from -r ./requirements.txt (line 1))
      Using cached https://files.pythonhosted.org/packages/ec/be/5ab8abdd8663c0386ec2dd595a5bc0e23330a0549b8a91e32f38c20845b6/lxml-4.4.1-cp36-cp36m-manylinux1_x86_64.whl
    Collecting cssselect (from -r ./requirements.txt (line 2))
      Using cached https://files.pythonhosted.org/packages/3b/d4/3b5c17f00cce85b9a1e6f91096e1cc8e8ede2e1be8e96b87ce1ed09e92c5/cssselect-1.1.0-py2.py3-none-any.whl
    Collecting Pillow (from -r ./requirements.txt (line 3))
      Using cached https://files.pythonhosted.org/packages/10/5c/0e94e689de2476c4c5e644a3bd223a1c1b9e2bdb7c510191750be74fa786/Pillow-6.2.1-cp36-cp36m-manylinux1_x86_64.whl
    Collecting requests (from -r ./requirements.txt (line 4))
      Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
    Collecting pycryptodome (from -r ./requirements.txt (line 5))
      Using cached https://files.pythonhosted.org/packages/c1/f1/0ba99559391621280ce24adea245d31bf2eb2f20ac72270eead1813e8d2b/pycryptodome-3.9.0-cp36-cp36m-manylinux1_x86_64.whl
    Collecting cloudscraper (from -r ./requirements.txt (line 6))
      Using cached https://files.pythonhosted.org/packages/85/7f/4239af8d3682f195d8c48e6b47e138073f663dfb55472f7d9dc463935924/cloudscraper-1.2.5-py2.py3-none-any.whl
    Collecting progressbar2 (from -r ./requirements.txt (line 7))
      Using cached https://files.pythonhosted.org/packages/16/68/adc395e0a3c86571081c8a2e2daaa5b58270f6854276a089a0e9b5fa2c33/progressbar2-3.47.0-py2.py3-none-any.whl
    Collecting urllib3 (from -r ./requirements.txt (line 8))
      Using cached https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl
    Collecting packaging (from -r ./requirements.txt (line 9))
      Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
    Collecting html-purifier (from -r ./requirements.txt (line 10))
    Collecting selenium (from -r ./requirements.txt (line 11))
    Using cached https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl
    Collecting pyexecjs (from -r ./requirements.txt (line 12))
    Collecting numpy (from -r ./requirements.txt (line 13))
      Using cached https://files.pythonhosted.org/packages/0e/46/ae6773894f7eacf53308086287897ec568eac9768918d913d5b9d366c5db/numpy-1.17.3-cp36-cp36m-manylinux1_x86_64.whl
    Collecting loguru (from -r ./requirements.txt (line 14))
      Using cached https://files.pythonhosted.org/packages/d5/db/669c5927e31c47c1cf5beef7ee784cc5fe88f95f47a86c5814a4f3de45f6/loguru-0.3.2-py3-none-any.whl
    Collecting idna<2.9,>=2.5 (from requests->-r ./requirements.txt (line 4))
      Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
    Collecting certifi>=2017.4.17 (from requests->-r ./requirements.txt (line 4))
      Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
    Collecting chardet<3.1.0,>=3.0.2 (from requests->-r ./requirements.txt (line 4))
      Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
    Collecting requests-toolbelt>=0.9.1 (from cloudscraper->-r ./requirements.txt (line 6))
      Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl
    Collecting brotli>=1.0.7 (from cloudscraper->-r ./requirements.txt (line 6))
      Using cached https://files.pythonhosted.org/packages/f4/68/60a220454dc5083c6d59b41aa90bb1c96fad62a0abf3a33e0ef64b38638a/Brotli-1.0.7-cp36-cp36m-manylinux1_x86_64.whl
    Collecting js2py>=0.60 (from cloudscraper->-r ./requirements.txt (line 6))
    Collecting pyopenssl>=17.0 (from cloudscraper->-r ./requirements.txt (line 6))
      Using cached https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl
    Collecting python-utils>=2.3.0 (from progressbar2->-r ./requirements.txt (line 7))
      Using cached https://files.pythonhosted.org/packages/eb/a0/19119d8b7c05be49baf6c593f11c432d571b70d805f2fe94c0585e55e4c8/python_utils-2.3.0-py2.py3-none-any.whl
    Collecting six (from progressbar2->-r ./requirements.txt (line 7))
      Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
    Collecting pyparsing>=2.0.2 (from packaging->-r ./requirements.txt (line 9))
      Using cached https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
    Collecting pyjsparser>=2.5.1 (from js2py>=0.60->cloudscraper->-r ./requirements.txt (line 6))
    Collecting tzlocal>=1.2 (from js2py>=0.60->cloudscraper->-r ./requirements.txt (line 6))
      Using cached https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl
    Collecting cryptography>=2.3 (from pyopenssl>=17.0->cloudscraper->-r ./requirements.txt (line 6))
      Using cached https://files.pythonhosted.org/packages/45/73/d18a8884de8bffdcda475728008b5b13be7fbef40a2acc81a0d5d524175d/cryptography-2.8-cp34-abi3-manylinux1_x86_64.whl
    Collecting pytz (from tzlocal>=1.2->js2py>=0.60->cloudscraper->-r ./requirements.txt (line 6))
      Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
    Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.3->pyopenssl>=17.0->cloudscraper->-r ./requirements.txt (line 6))
      Using cached https://files.pythonhosted.org/packages/ab/15/d6bd2c322da944ba74ca545dd5e4af6e1e72339cbbc738e6877e349cdfbe/cffi-1.13.1-cp36-cp36m-manylinux1_x86_64.whl
    Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.3->pyopenssl>=17.0->cloudscraper->-r ./requirements.txt (line 6))
      Using cached https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
    Building wheels for collected packages: pycparser
      Running setup.py bdist_wheel for pycparser ... error
      Complete output from command /manga-py/my_env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-eor4ym6x/pycparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpsao964sepip-wheel- --python-tag cp36:
      usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
        or: -c --help [cmd1 cmd2 ...]
        or: -c --help-commands
        or: -c cmd --help

      error: invalid command 'bdist_wheel'

      ----------------------------------------
      Failed building wheel for pycparser
      Running setup.py clean for pycparser
    Failed to build pycparser
    Installing collected packages: lxml, cssselect, Pillow, urllib3, idna, certifi, chardet, requests, pycryptodome, requests-toolbelt, brotli, six, pyjsparser, pytz, tzlocal, js2py, pycparser, cffi, cryptography, pyopenssl, cloudscraper, python-utils, progressbar2, pyparsing, packaging, html-purifier, selenium, pyexecjs, numpy, loguru
      Running setup.py install for pycparser ... done
    Successfully installed Pillow-6.2.1 brotli-1.0.7 certifi-2019.9.11 cffi-1.13.1 chardet-3.0.4 cloudscraper-1.2.5 cryptography-2.8 cssselect-1.1.0 html-purifier-0.1.9 idna-2.8 js2py-0.66 loguru-0.3.2 lxml-4.4.1 numpy-1.17.3 packaging-19.2 progressbar2-3.47.0 pycparser-2.19 pycryptodome-3.9.0 pyexecjs-1.5.1 pyjsparser-2.7.1 pyopenssl-19.0.0 pyparsing-2.4.2 python-utils-2.3.0 pytz-2019.3 requests-2.22.0 requests-toolbelt-0.9.1 selenium-3.141.0 six-1.12.0 tzlocal-2.0.0 urllib3-1.25.6
    ```
7. repeat step 5 (resee installed modules, under a virtual-env);
    ```
    (my_env) $ pip freeze
    Brotli==1.0.7
    certifi==2019.9.11
    cffi==1.13.1
    chardet==3.0.4
    cloudscraper==1.2.5
    cryptography==2.8
    cssselect==1.1.0
    html-purifier==0.1.9
    idna==2.8
    Js2Py==0.66
    loguru==0.3.2
    lxml==4.4.1
    numpy==1.17.3
    packaging==19.2
    Pillow==6.2.1
    pkg-resources==0.0.0
    progressbar2==3.47.0
    pycparser==2.19
    pycryptodome==3.9.0
    PyExecJS==1.5.1
    pyjsparser==2.7.1
    pyOpenSSL==19.0.0
    pyparsing==2.4.2
    python-utils==2.3.0
    pytz==2019.3
    requests==2.22.0
    requests-toolbelt==0.9.1
    selenium==3.141.0
    six==1.12.0
    tzlocal==2.0.0
    urllib3==1.25.6
    ```
8. run tests from manga-py `./pytest.py`, results an error `ModuleNotFoundError` (`pyvirtualdisplay`);
    ```
    (my_env) $python3 ./pytest.py
    Traceback (most recent call last):
      File "./pytest.py", line 8, in <module>
        from tests import *
      File "/manga-py/manga-py/tests/__init__.py", line 7, in <module>
        from .web_driver import TestWebDriver
      File "/manga-py/manga-py/tests/web_driver.py", line 3, in <module>
        from pyvirtualdisplay import Display
    ModuleNotFoundError: No module named 'pyvirtualdisplay'
    ```
9. install `pyvirtualdisplay`;
    ```
    (my_env) $ pip3 install pyvirtualdisplay
    Collecting pyvirtualdisplay
      Downloading https://files.pythonhosted.org/packages/cf/ad/b15f252bfb0f1693ad3150b55a44a674f3cba711cacdbb9ae2f03f143d19/PyVirtualDisplay-0.2.4-py2.py3-none-any.whl
    Collecting EasyProcess (from pyvirtualdisplay)
      Downloading https://files.pythonhosted.org/packages/fa/29/40040d1d64a224a5e44df9572794a66494618ffe5c77199214aeceedb8a7/EasyProcess-0.2.7-py2.py3-none-any.whl
    Installing collected packages: EasyProcess, pyvirtualdisplay
    Successfully installed EasyProcess-0.2.7 pyvirtualdisplay-0.2.4
    ```
10. repeat step 8 (rerun tests), now with success.
    ```
    (my_env) $ python3 ./pytest.py
    ..................................................
    ----------------------------------------------------------------------
    Ran 50 tests in 72.267s

    OK
    ```
11. create `./requirements_dev.txt`, to install the base modules + `pyvirtualdisplay` module;
    ```
    (my_env) $ touch ./requirements_dev.txt
    (my_env) $ echo "-r ./requirements.txt" >> ./requirements_dev.txt
    (my_env) $ echo "pyvirtualdisplay" >> ./requirements_dev.txt
    ```
12. see `./requirements`;
    ```
    (my_env) $ cat ./requirements.txt
    lxml
    cssselect
    Pillow
    requests
    pycryptodome
    cloudscraper
    progressbar2
    urllib3
    packaging
    html-purifier
    selenium
    pyexecjs
    numpy
    loguru

    (my_env) $ cat ./requirements_dev.txt
    -r ./requirements.txt
    pyvirtualdisplay
    ```
13. see installed modules;
    ```
    (my_env) $ pip freeze
    Brotli==1.0.7
    certifi==2019.9.11
    cffi==1.13.1
    chardet==3.0.4
    cloudscraper==1.2.5
    cryptography==2.8
    cssselect==1.1.0
    EasyProcess==0.2.7
    html-purifier==0.1.9
    idna==2.8
    Js2Py==0.66
    loguru==0.3.2
    lxml==4.4.1
    numpy==1.17.3
    packaging==19.2
    Pillow==6.2.1
    pkg-resources==0.0.0
    progressbar2==3.47.0
    pycparser==2.19
    pycryptodome==3.9.0
    PyExecJS==1.5.1
    pyjsparser==2.7.1
    pyOpenSSL==19.0.0
    pyparsing==2.4.2
    python-utils==2.3.0
    pytz==2019.3
    PyVirtualDisplay==0.2.4
    requests==2.22.0
    requests-toolbelt==0.9.1
    selenium==3.141.0
    six==1.12.0
    tzlocal==2.0.0
    urllib3==1.25.6
    ```

Results
=======

Bellow are listed a before and after states when this commit is applied:

- Before this commit:
```
(my_env) $ cat ./requirements.txt
lxml
cssselect
Pillow
requests
pycryptodome
cloudscraper
progressbar2
urllib3
packaging
html-purifier
selenium
pyexecjs
numpy
loguru

(my_env) $ python3 ./pytest.py
Traceback (most recent call last):
  File "./pytest.py", line 8, in <module>
    from tests import *
  File "/manga-py/manga-py/tests/__init__.py", line 7, in <module>
    from .web_driver import TestWebDriver
  File "/manga-py/manga-py/tests/web_driver.py", line 3, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'
```

- After this commit:
```
(my_env) $ cat ./requirements.txt
lxml
cssselect
Pillow
requests
pycryptodome
cloudscraper
progressbar2
urllib3
packaging
html-purifier
selenium
pyexecjs
numpy
loguru

(my_env) $ cat ./requirements_dev.txt
-r ./requirements.txt
pyvirtualdisplay

(my_env) $ python3 ./pytest.py
..................................................
----------------------------------------------------------------------
Ran 50 tests in 72.267s
OK
```

Future work
===========

- Ask if this problem occurred with other people.
- Ask if bellow files need to be updated, or be synchronized with each other:
    - `requirements.txt`
    - `.scrutinizer.yml`
    - `.travis.yml`
    - ...others files?
- The CI third-party systems did not warning that dependence issue?
- Is `./pytest.py` to be runned with [pytest module](https://docs.pytest.org/en/latest/) or with [unittest building](https://docs.python.org/3/library/unittest.html)?
- Every time I run the tests, git annoying me with (undesired) untracked/unstaged files. How to resolve that?
    ```
    (my_env) $ git status
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

            modified:   helpers/gh_pages_content/improvement.html
            modified:   helpers/gh_pages_content/index.html

    Untracked files:
      (use "git add <file>..." to include in what will be committed)

            helpers/gh_pages_content/providers.json
    ```